# -*- coding: utf-8 -*-
"""analise1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uTWv58PRTb0ietPYJ74QavElBHBzkUeO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

detran = pd.read_csv(r'datatran2020.csv', encoding='ISO-8859-1', sep=';')

df_detran = pd.DataFrame(detran)
df_detran

pd.set_option("display.max.columns", None)

sns.set_style("dark")

ax = sns.countplot(y = 'uf', data = df_detran, color = 'LimeGreen', order= df_detran['uf'].value_counts().index)
plt.title("Número de acidentes por estado")
plt.xlabel("Número de casos")
plt.ylabel("Estado")

ax = sns.countplot(y = 'causa_acidente', data = df_detran, color = 'LimeGreen', order= df_detran['causa_acidente'].value_counts().head(5).index)
plt.title("Motivos dos acidentes nas rodovias")
plt.xlabel("Número de casos")
plt.ylabel("Motivos")

df_causa = df_detran['causa_acidente'].value_counts().head(5)
print(df_causa)

ax = sns.countplot(y = 'dia_semana', data = df_detran, color = 'LimeGreen', order= df_detran['dia_semana'].value_counts().head(3).index)
plt.title("Dias da semana com o maior número de acidentes")
plt.xlabel("Número de casos")
plt.ylabel("Dia da semana")

df_mortes = df_detran['mortos'].sum()
print(df_mortes)

df_feridos_graves = df_detran['feridos_graves'].sum()
print(df_feridos_graves)

df_feridos_leves = df_detran['feridos_leves'].sum()
print(df_feridos_leves)

df_ilesos = df_detran['ilesos'].sum()
print(df_ilesos)

data = np.array([['Feridos graves',17104],
                 ['Feridos leves',54376],
                 ['Ilesos',60858],
                 ['Mortes',5271]])
print(data)
df = pd.DataFrame(data, index=range(1,5),columns=['Situação', 'Número'])
print(df)

